# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tpch'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Variables for dbt project evaluator - bronze layer configuration
vars:
  dbt_project_evaluator:
    # Map bronze layer to staging conventions
    staging_folder_name: "a_bronze"
    model_types: ['staging']  # Only evaluate staging/bronze layer
    
    # Focus on primary key and documentation tests only
    test_coverage_target: 100
    documentation_coverage_target: 100
    
    # Exclude silver, gold, and metrics layers 
  exclude_paths_from_project: 
    - "models/b_silver/"
    - "models/c_gold/" 
    - "models/metrics/"

# Disable most evaluator checks - keep only primary key and documentation
models:
  dbt_project_evaluator:
    marts:
      dag:
        +enabled: false  # Disable all DAG-related checks
      performance:
        +enabled: false  # Disable performance checks
      structure:
        +enabled: false  # Disable structure checks  
      governance:
        +enabled: false  # Disable governance checks
      tests:
        fct_test_coverage:
          +enabled: true   # Keep test coverage
        fct_missing_primary_key_tests:
          +enabled: true   # Keep primary key tests
        fct_sources_without_freshness:
          +enabled: false  # Disable freshness checks
      documentation:
        +enabled: true     # Keep all documentation checks

flags:
  require_generic_test_arguments_property: true