models:
  - name: agg_order_revenue
    access: public
    description: This model aggregates revenue data from customer orders by year, returnflag, shipmode, region, and nation.
    columns:
      - name: year
        description: The year in which the orders were placed.
        tests:
          - not_null
          - valid_year_range:
              start_year: 1990
              end_year: 1999
      - name: returnflag
        description: Indicates if the order was returned.
        tests:
          - not_null
      - name: shipmode
        description: The mode of shipment for the orders. "{{doc('shipping_mode')}}"
        tests:
          - not_null
      - name: region_name
        description: The name of the region where the order originated.
        tests:
          - not_null
      - name: nation_name
        description: The name of the nation where the order originated.
        tests:
          - not_null
      - name: total_revenue
        description: The total revenue from customer orders for the specified year, returnflag, shipmode, region, and nation.
        tests:
          - not_null
          - non_negative:
              config:
                store_failures: true  # store failures for this test
          - unique_nation_region:
              config:
                store_failures: true  # store failures for this test